### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by jonathanjm** [titan-suite/cli#2]
When I try to deploy a contract I get the following error:
>(node:22498) UnhandledPromiseRejectionWarning: Error: Action not allowed
    at Object.InvalidResponse (/usr/local/lib/node_modules/@titan-suite/cli/node_modules/aion-web3/lib/web3/errors.js:38:16)
    at /usr/local/lib/node_modules/@titan-suite/cli/node_modules/aion-web3/lib/web3/requestmanager.js:88:36
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/@titan-suite/cli/node_modules/aion-web3/lib/web3/httpprovider.js:120:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/@titan-suite/cli/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/@titan-suite/cli/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/@titan-suite/cli/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@titan-suite/cli/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:22498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.

----
The deploy is using the first account on the accounts list.

**Comment by ToJen** [comment]
Thanks @jonathanjm, looks like the account isn't unlocked yet. I'll fix the selection of the origin address for deployment.

**Comment by ToJen** [comment]
It's been fixed now with commit 116171f9dbb3ee45cf3d4c4f6a7a833be5194ea3. Let me know how it goes!
